name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Real-Estate-Integrated-Project
            git pull origin main
            sudo docker build -t backend:latest ./backend
            sudo docker build -t frontend:latest ./frontend
            sudo docker save backend:latest > backend.tar
            sudo docker save frontend:latest > frontend.tar
            sudo k3s ctr images import backend.tar
            sudo k3s ctr images import frontend.tar
            sudo k3s kubectl apply -f k8s/
            sudo k3s kubectl apply -f k8s/ingress.yaml
            sudo k3s kubectl rollout restart deployment/frontend
            sudo k3s kubectl rollout restart deployment/backend
